# Generated by Django 2.1.2 on 2018-10-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchapp', '0002_auto_20181023_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='linkedin_id',
            new_name='indeed_id',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='location',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
