# Generated by Django 2.1.2 on 2018-10-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchapp', '0003_auto_20181024_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='company',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
