# Generated by Django 2.1.2 on 2018-11-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchapp', '0004_joblisting_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='indeed_id',
            field=models.CharField(max_length=200),
        ),
    ]
