# Generated by Django 2.1.2 on 2018-11-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchapp', '0005_auto_20181104_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=models.TextField(max_length=20000),
        ),
    ]
