# Generated by Django 2.1.2 on 2018-11-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchapp', '0006_auto_20181104_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='indeed_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
