# Generated by Django 2.1.2 on 2019-04-25 01:36

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elasticsearchapp', '0007_auto_20181104_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=None)),
                ('locations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=None)),
                ('companies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=None)),
                ('titles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=None)),
                ('title', models.CharField(max_length=200)),
                ('insights', django.contrib.postgres.fields.jsonb.JSONField()),
                ('top_skills', django.contrib.postgres.fields.jsonb.JSONField()),
                ('blacklist', models.CharField(max_length=200)),
                ('whitelist', models.CharField(max_length=200)),
                ('custom', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
