# Generated by Django 2.1.2 on 2019-04-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchapp', '0013_auto_20190429_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtile',
            old_name='user',
            new_name='user_id',
        ),
    ]
