# Generated by Django 2.1.2 on 2019-04-29 08:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchapp', '0014_auto_20190429_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardTile',
            fields=[
                ('tile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elasticsearchapp.Tile')),
                ('style', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            bases=('elasticsearchapp.tile',),
        ),
    ]
