# Generated by Django 2.1.2 on 2019-05-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchapp', '0015_standardtile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
